development:
  adapter: postgresql
  encoding: unicode
  database: ownmarket_development
  pool: 5
  username: jk

test:
  adapter: postgresql
  encoding: unicode
  database: ownmarket_test
  pool: 5
  username: jk

# TODO set up a production db!
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: ownmarket_production
#   pool: 5
#   username: myapp
